spring:
  profiles:
    active: 
    - dev
        
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: springcloud-config-dept-client
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 5
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.handsome.springcloud.api.entities
  mapper-locations:
  - classpath:mybatis/mappers/**/*.xml
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app.name: handsome-springcloud
  company.name: www.handsome.com
  build.atrifactId: $project.artifactId$
  build.version: $project.version$     
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: springcloud-config-dept-client
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb02
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 5
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.handsome.springcloud.api.entities
  mapper-locations:
  - classpath:mybatis/mappers/**/*.xml
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app.name: handsome-springcloud
  company.name: www.handsome.com
  build.atrifactId: $project.artifactId$
  build.version: $project.version$    